DROP TABLE IF EXISTS BASIC_SPENDING;
DROP TABLE IF EXISTS PERIODICAL_SPENDING;

CREATE SCHEMA SPENDING;

CREATE TABLE SPENDING.BASIC_SPENDING(
    ID INT,
    AMOUNT DECIMAL NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    TYPE VARCHAR(255) NOT NULL,
    PAY_DATE DATE NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE SPENDING.PERIODICAL_SPENDING(
    ID INT,
    AMOUNT DECIMAL NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    TYPE VARCHAR(255) NOT NULL,
    START_DATE DATE NOT NULL,
    PAY_DATE DATE NOT NULL,
    PRIMARY KEY (ID)
);

CREATE SEQUENCE SPENDING.SEQ_BASIC_SPENDING
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SPENDING.SEQ_PERIODICAL_SPENDING
START WITH 1
INCREMENT BY 1;

INSERT INTO SPENDING.BASIC_SPENDING(ID, AMOUNT, NAME , TYPE, PAY_DATE)
VALUES ((SELECT NEXT VALUE FOR SPENDING.SEQ_BASIC_SPENDING), 10.20, 'Buying', 'BUY', '2021-04-01');

INSERT INTO SPENDING.PERIODICAL_SPENDING(ID, AMOUNT, NAME , TYPE, START_DATE, PAY_DATE)
VALUES ((SELECT NEXT VALUE FOR SPENDING.SEQ_PERIODICAL_SPENDING), 10.20, 'INSURANCE', 'SERVICE_SUSCRIPTION', '2021-02-01', '2021-03-14');
INSERT INTO SPENDING.PERIODICAL_SPENDING(ID, AMOUNT, NAME , TYPE, START_DATE, PAY_DATE)
VALUES ((SELECT NEXT VALUE FOR SPENDING.SEQ_PERIODICAL_SPENDING), 50.70, 'Car debit', 'DIRECT_DEBIT', '2021-03-02', SYSDATE());