INSERT INTO SPENDING.BASIC_SPENDING(ID, AMOUNT, NAME , TYPE, PAY_DATE)
VALUES ((SELECT NEXT VALUE FOR SPENDING.SEQ_BASIC_SPENDING), 10.20, 'Buying', 'BUY', '2021-04-01');

INSERT INTO SPENDING.PERIODICAL_SPENDING(ID, AMOUNT, NAME , TYPE, START_DATE, PAY_DATE)
VALUES ((SELECT NEXT VALUE FOR SPENDING.SEQ_PERIODICAL_SPENDING), 10.20, 'INSURANCE', 'SERVICE_SUSCRIPTION', '2021-02-01', '2021-03-14');
INSERT INTO SPENDING.PERIODICAL_SPENDING(ID, AMOUNT, NAME , TYPE, START_DATE, PAY_DATE)
VALUES ((SELECT NEXT VALUE FOR SPENDING.SEQ_PERIODICAL_SPENDING), 50.70, 'Car debit', 'DIRECT_DEBIT', '2021-03-02', SYSDATE());