DROP TABLE IF EXISTS BASIC_SPENDING;
DROP TABLE IF EXISTS PERIODICAL_SPENDING;

CREATE SCHEMA SPENDING;

CREATE TABLE SPENDING.BASIC_SPENDING(
    ID INT,
    AMOUNT DECIMAL NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    TYPE VARCHAR(255) NOT NULL,
    PAY_DATE DATE NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE SPENDING.PERIODICAL_SPENDING(
    ID INT,
    AMOUNT DECIMAL NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    TYPE VARCHAR(255) NOT NULL,
    START_DATE DATE NOT NULL,
    PAY_DATE DATE NOT NULL,
    PRIMARY KEY (ID)
);

CREATE SEQUENCE SPENDING.SEQ_BASIC_SPENDING
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SPENDING.SEQ_PERIODICAL_SPENDING
START WITH 1
INCREMENT BY 1;